Repository prgrms-be-devcourse/NBE7-9-1-Team04, pull requests merged in 2025-09, with the labels that each got.

#8 feat : User 엔티티 추가
  backend/src/main/java/com/backend/domain/user/user/controller/UserController.java
  backend/src/main/java/com/backend/domain/user/user/dto/UserDto.java
  backend/src/main/java/com/backend/domain/user/user/entity/User.java
  backend/src/main/java/com/backend/domain/user/user/service/UserService.java
Labels: ✨ feature

#22 feat: Order 테이블 명 수정
  backend/src/main/java/com/backend/domain/order/entity/Order.java
Labels: 🐛fix

#23 feat: 장바구니 엔티티 생성
  backend/src/main/java/com/backend/domain/cart/entity/Cart.java
  backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
Labels: ✨ feature

#25 feat: menu 엔티티 ERD 칼럼 매핑 삭제
  backend/src/main/java/com/backend/domain/menu/entity/Menu.java
Labels: ♻️ refactor

#29 fix:import 수정
  backend/src/main/java/com/backend/domain/order/dto/OrderDto.java
Labels: 🐛fix

#37 test: 도메인별 test 패키지 생성
  backend/src/test/java/com/backend/domain/cart/controller/dummyFile
  backend/src/test/java/com/backend/domain/cart/service/dummyFile
  backend/src/test/java/com/backend/domain/menu/controller/dummyFile
  backend/src/test/java/com/backend/domain/menu/service/dummyFile
  backend/src/test/java/com/backend/domain/order/controller/dummyFile
  backend/src/test/java/com/backend/domain/order/service/dummyFile
  backend/src/test/java/com/backend/domain/payment/controller/dummyFile
  backend/src/test/java/com/backend/domain/payment/service/dummyFile
  backend/src/test/java/com/backend/domain/user/controller/dummyFile
  backend/src/test/java/com/backend/domain/user/service/dummyFile
Labels: 🚨 test

#39 feature: 장바구니 메뉴 추가 기능 구현
  backend/src/main/java/com/backend/domain/cart/controller/CartController.java
  backend/src/main/java/com/backend/domain/cart/controller/dto/request/CartAddRequest.java
  backend/src/main/java/com/backend/domain/cart/controller/dto/response/CartResponse.java
  backend/src/main/java/com/backend/domain/cart/repository/CartRepository.java
  backend/src/main/java/com/backend/domain/cart/service/CartService.java
  backend/src/main/java/com/backend/global/exception/BusinessException.java
  backend/src/main/java/com/backend/global/exception/GlobalExceptionHandler.java
Labels: ✨ feature

#48 feature(address) : 주소 저장할 address 엔티티 클래스 추가
  backend/src/main/java/com/backend/domain/user/address/dto/AddressDto.java
  backend/src/main/java/com/backend/domain/user/address/entity/Address.java
  backend/src/main/java/com/backend/domain/user/address/repository/AddressRepository.java
  backend/src/main/java/com/backend/domain/user/address/service/AddressService.java
Labels: ✨ feature

#49 feat: 주문 생성,상태 변경 기능 추가
  backend/src/main/java/com/backend/domain/order/controller/OrderController.java
  backend/src/main/java/com/backend/domain/order/dto/OrderDto.java
  backend/src/main/java/com/backend/domain/order/dto/request/OrderCreateRequest.java
  backend/src/main/java/com/backend/domain/order/dto/request/OrderDetailsCreateRequest.java
  backend/src/main/java/com/backend/domain/order/dto/request/OrderStatusUpdateRequest.java
  backend/src/main/java/com/backend/domain/order/dto/response/OrderCreateResponse.java
  backend/src/main/java/com/backend/domain/order/dto/response/OrderDetailsCreateResponse.java
  backend/src/main/java/com/backend/domain/order/entity/OrderDetails.java
  backend/src/main/java/com/backend/domain/order/entity/OrderStatus.java
  backend/src/main/java/com/backend/domain/order/entity/Orders.java
  backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/backend/global/response/ErrorCode.java
Labels: ✨ feature

#55 feature(rq) : 쿠키, 헤더 처리를 동시에 해줄 전역 클래스
  backend/src/main/java/com/backend/global/rq/Rq.java
Labels: ✨ feature

#56 feat: 메뉴 생성 기능 추가
  backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
  backend/src/main/java/com/backend/domain/menu/dto/MenuAddRequest.java
  backend/src/main/java/com/backend/domain/menu/dto/MenuResponse.java
  backend/src/main/java/com/backend/domain/menu/entity/Menu.java
  backend/src/main/java/com/backend/domain/menu/repository/MenuRepository.java
  backend/src/main/java/com/backend/domain/menu/service/MenuService.java
  backend/src/main/java/com/backend/global/response/ErrorCode.java
Labels: ✨ feature

#57 feat: 장바구니 메뉴 수량 변경 기능 구현
  backend/src/main/java/com/backend/domain/cart/controller/CartController.java
  backend/src/main/java/com/backend/domain/cart/service/CartService.java
Labels: ✨ feature

#61 feature: 장바구니 메뉴 삭제 기능 구현
  backend/src/main/java/com/backend/domain/cart/controller/CartController.java
  backend/src/main/java/com/backend/domain/cart/service/CartService.java
Labels: ✨ feature

#80 feature: 장바구니 전체 삭제 기능 구현
  backend/src/main/java/com/backend/domain/cart/controller/CartController.java
  backend/src/main/java/com/backend/domain/cart/repository/CartRepository.java
  backend/src/main/java/com/backend/domain/cart/service/CartService.java
Labels: ✨ feature

#81 feat: 메뉴 수정 기능 추가
  backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
  backend/src/main/java/com/backend/domain/menu/dto/MenuUpdateRequest.java
  backend/src/main/java/com/backend/domain/menu/entity/Menu.java
  backend/src/main/java/com/backend/domain/menu/repository/MenuRepository.java
  backend/src/main/java/com/backend/domain/menu/service/MenuService.java
Labels: ✨ feature

#82 feature: 사용자 주문 조회 기능 추가
  backend/src/main/java/com/backend/domain/order/controller/OrderController.java
  backend/src/main/java/com/backend/domain/order/dto/request/OrderCreateRequest.java
  backend/src/main/java/com/backend/domain/order/dto/request/OrderDetailsCreateRequest.java
  backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryDetailResponse.java
  backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryResponse.java
  backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/backend/domain/order/service/OrderService.java
Labels: ♻️ refactor, ✨ feature

#83 feature(user) : 사용자 정보 조회 구현, 사용자 정보 수정 구현, 예외 처리 방식 일원화
  backend/src/main/java/com/backend/domain/user/user/controller/UserController.java
  backend/src/main/java/com/backend/domain/user/user/entity/Users.java
  backend/src/main/java/com/backend/domain/user/user/service/UserService.java
  backend/src/main/java/com/backend/global/response/ErrorCode.java
Labels: 🐛fix, ♻️ refactor, ✨ feature

#102 refactor(menu): 엔티티 개선 및 관리자 권한 검증 로직 개선
  backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
  backend/src/main/java/com/backend/domain/menu/dto/MenuAddRequest.java
  backend/src/main/java/com/backend/domain/menu/dto/MenuUpdateRequest.java
  backend/src/main/java/com/backend/domain/menu/entity/Menu.java
  backend/src/main/java/com/backend/domain/menu/service/MenuService.java
Labels: ♻️ refactor

#112 feature: 결제 단건 취소 API
  backend/src/main/java/com/backend/domain/payment/controller/PaymentController.java
  backend/src/main/java/com/backend/domain/payment/dto/response/PaymentCancelResponse.java
  backend/src/main/java/com/backend/domain/payment/entity/Payment.java
  backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
  backend/src/main/java/com/backend/global/response/ErrorCode.java
Labels: ✨ feature

#117 chore: api 설계에 맞춘 네이밍 변경
  backend/src/main/java/com/backend/domain/cart/controller/CartController.java
  backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
  backend/src/main/java/com/backend/global/config/SpringDoc.java
Labels: 🔧 chore

#119 feat: 결제 단건 삭제 API, Payment 도메인 전반 사용자 검증 도입
  backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/backend/domain/payment/controller/PaymentController.java
  backend/src/main/java/com/backend/domain/payment/entity/Payment.java
  backend/src/main/java/com/backend/domain/payment/entity/PaymentStatus.java
  backend/src/main/java/com/backend/domain/payment/repository/PaymentRepository.java
  backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
  backend/src/main/java/com/backend/global/response/ErrorCode.java
Labels: ✨ feature

#122 fix: 메뉴 컨트롤러 관리자 권한 레벨 수정
  backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
Labels: 🐛fix

#138 Fix(user), refactor(address) : 사용자 로그아웃 버그 수정, 주소 디비 조회횟수 감소
  backend/src/main/java/com/backend/domain/user/address/entity/Address.java
  backend/src/main/java/com/backend/domain/user/address/service/AddressService.java
  backend/src/main/java/com/backend/domain/user/user/controller/UserController.java
  backend/src/main/java/com/backend/domain/user/user/dto/UserDto.java
  backend/src/main/java/com/backend/domain/user/user/entity/Users.java
  backend/src/main/java/com/backend/domain/user/user/service/UserService.java
Labels: 🐛fix, ♻️ refactor

#140 refactor: 결제 요청 시 성공/승인에 따른 상태 변화 코드 수정
  backend/build.gradle
  backend/src/main/java/com/backend/BackendApplication.java
  backend/src/main/java/com/backend/domain/payment/entity/Payment.java
  backend/src/main/java/com/backend/domain/payment/service/PaymentFactory.java
  backend/src/main/java/com/backend/domain/payment/service/PaymentProcessor.java
  backend/src/main/java/com/backend/domain/payment/service/PaymentRetry.java
  backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
  backend/src/main/java/com/backend/domain/payment/service/RandomPaymentProcessor.java
  backend/src/test/java/com/backend/domain/payment/service/PaymentServiceTest.java
  backend/src/test/java/com/backend/domain/payment/service/dummyFile
Labels: ♻️ refactor

#141 feature: 메뉴/관리자 대시보드 페이지 구현
  backend/src/main/java/com/backend/global/WebConfig/WebConfig.java
  frontend/src/app/admin/page.tsx
  frontend/src/app/menu/page.tsx
Labels: ✨ feature

#145 refactor: 주문-결제 취소, 삭제 연동
  backend/src/main/java/com/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
Labels: ♻️ refactor

#146 feature : 주문/결제 페이지 구성
  backend/src/main/java/com/backend/domain/order/dto/response/AdminOrderSummaryResponse.java
  backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryDetailResponse.java
  backend/src/main/java/com/backend/domain/order/service/AdminOrderService.java
  backend/src/main/java/com/backend/domain/order/service/OrderService.java
  frontend/src/app/orders/admin/page.tsx
  frontend/src/app/orders/page.tsx
  frontend/src/app/payment/page.tsx
Labels: ✨ feature

#154 [FE] feature: 헤더 기능 구현
  frontend/next.config.ts
  frontend/src/app/layout.tsx
  frontend/src/components/header.tsx
  frontend/src/context/AuthContext.tsx
Labels: ✨ feature

#156 fix:[FE] 주문 취소,삭제 시 결제->주문 순으로 취소,삭제 되게 설정
  frontend/src/app/orders/page.tsx
Labels: 🐛fix

#158 chore: 테스트를 위한 기본 메뉴 추가
  backend/src/main/java/com/backend/global/init/BaseInitData.java
Labels: 🔧 chore

#161 feat: 스케줄러 도입
  backend/src/main/java/com/backend/BackendApplication.java
  backend/src/main/java/com/backend/domain/order/entity/Orders.java
  backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/backend/global/scheduler/OrderScheduler.java
  backend/src/test/java/com/backend/global/scheduler/OrderSchedulerTest.java
Labels: ✨ feature

#163 feature: 메뉴 조회 개선(품절 포함), 장바구니 이동 UI추가
  backend/src/main/java/com/backend/domain/menu/service/MenuService.java
  frontend/src/app/menu/page.tsx
  frontend/src/components/header.tsx
  frontend/src/context/AuthContext.tsx
Labels: ✨ feature

#167 feature: 장바구니 담기 시 리패치, 관리자 권한 검증 후 주문목록 표출, 관리자 대시 보드 접근
  frontend/src/app/admin/page.tsx
  frontend/src/app/menu/page.tsx
  frontend/src/components/header.tsx
Labels: ✨ feature

#173 fix:결제 페이지 배송비 뜨게 수정 + 결제 내역 관련 수정
  frontend/src/app/orders/admin/page.tsx
  frontend/src/app/orders/page.tsx
  frontend/src/app/payment/page.tsx
Labels: ✨ feature

#175 refactor(FE): 로그인 상태에 따른 페이지 접근 제한
  frontend/src/app/cart/page.tsx
  frontend/src/components/auth/AuthGuard.tsx
Labels: ♻️ refactor

#182 refactor(payment): 장바구니 아이콘 refetch, 배송 주소, 결제 금액 UI, 로그인 접근
  backend/src/main/java/com/backend/domain/payment/service/RandomPaymentProcessor.java
  frontend/src/app/payment/fail/page.tsx
  frontend/src/app/payment/page.tsx
  frontend/src/app/payment/success/page.tsx
Labels: ♻️ refactor

#187 feat:[FE] 관리자 주문 조회 페이지 리펙토링 및 약간의 색상 변경
  frontend/src/app/orders/admin/page.tsx
  frontend/src/app/orders/page.tsx
  frontend/src/components/admin-order-card.tsx
  frontend/src/components/order-item.tsx
Labels: ♻️ refactor
